### ISSUE TITLE
Merge with solution_5

### ISSUE THREAD

**Issue by Kulasko** [mike-barber/daves-garage-primes#5]
For maximum performance, as well as the least amount of solutions and redundant code, it could be a good idea to merge the multi-threaded algorithm with your solution, because it's a bit faster. Also, it enables more effective scaling of test cases. For example, we could make the bit vector variants generic for different block sizes (u8 to u64).

However, doing this would require modifying the `FlagStorage` trait:
- There would need to be a way to get a slice of the internal Vector.
- `reset_flags` would be required to not work on `&mut self`, but on a slice. The reason is that it's effective threading is only possible by dividing the flag vector into non-overlapping slices.
- Implementing `FlagStorageBitVectorStriped` would yield incorrect results when calling `reset_flags` for everything but the full slice.

When doing this, is would also enable us to effectively implement all interesting versions of the wheel algorithm in the future, as well. However, it would also greatly increase the amount of code in your solution, as well.
Of course, we would only do this after we're finished with the idiomatic changes.

What are your thoughts on this?

**Comment by mike-barber** [comment]
The main issue with this idea is the complexity: it's going to be really hard work to ensure that performance is not lost while restructuring the solution. I've spent quite a long time profiling, tweaking, and improving my solution so that it's performant. FlagStorageBitVectorStriped would be pretty challenging to get right, definitely.

Bear in mind that the main competition is essentially single-thread, bit-level, `base`, `faithful` algorithm. Everything else (wheel, etc) is a bit of a side-show, and I'd prefer to keep this solution as targeted as possible. 

On the parallel front, one of the rules in the competition is `It uses no external dependencies to calculate the actual sieve.` In order to avoid any debates, I've decided _not_ to pull in Tokio, Rayon, etc. Consequently, my parallelism approach is designed to be as coarse-grained as possible: use OS threads, and run as many independent sieves as possible in 5s. This works really well, yielding around 180,000 for the fastest bits implementation on my machine: about 11.5X gain on 12 cores.

We don't gain anything by doing parallelism _within_ each sieve: it's still treated as a "parallel" algorithm, regardless of how it's done. I think it's really good to show how it's done within a single sieve (i.e. your solution_5), but it won't improve any performance numbers in this solution - the coarse-grained solution will usually win out as there is less overhead.

**Comment by Kulasko** [comment]
I do understand your concerns. Honestly, the main issue here would be the linker; at the current optimization level we're talking about, how the linker layouts the code and data probably has a larger influence then the prime search optimization we did recently. On the other hand, the whole benchmark basically should be one solid block of code at this point.
You are right that sharing a bit-reset function with my multi threaded algorithms would waste a few more clock cycles for calculating an offset that is always going to be zero.
I also wouldn't attempt to implement parallel algorithms for `FlagStorageBitVectorStriped` as this essentially can't scale because of its memory pattern. It would just be wasted effort.

I only partly agree here. In Dave's last video, he iterated that he is ranking the languages by single-bit, faithful implementations. However, he did not mention the base algorithm. But of course, I do understand that we're mostly looking for single threaded solutions and I also understand your desire to have a smaller, focused solution.

I do understand where you're coming from. I do think that this rule was created for solutions like one I saw recently in the pull requests, where someone tried to accelerate the Go code by calling C code in large parts. I think that using a general Rust library would be fine since `std` essentially is just that and `rbergen` didn't see to have a problem with it when looking at my solution. Ultimately, I still respect your wish to not invite debate with the maintainers.

I think it is really unfortunate that those two forms of parallelism are treated the same. With fully independent parallel sieve solving, a near-linear speedup is to be expected as long as the cores don't exhaust some shared resource (which is unlikely with this type of workload, apart from boost clocks because of power).

So in total, you seem to disagree with my proposal. As an alternative, would you agree to me partly reusing your code structure and also maybe make the `BitVector` variants generic to their inner type, so Rust can win with whatever type works best on Dave's machine?

**Comment by mike-barber** [comment]
Thanks for taking the time to go through this. I think I'm being a bit more risk-averse with this than usual: the solution has been in there for quite a while and it's had a lot of tweaks. 

I'm reasonably sure that Dave's really looking for the `base` algorithms, but there might be a special mention for some of the more interesting `wheel` ones too.

I think my main objective with this is to give Rust a good result when compared head-to-head with everything else. I think we're doing ok there. And it'll be good if the code is still simple enough to understand when someone new to the language is interested in it, and has a look. In other words, it's possible to get really good performance out of it without having to understand a very complex ecosystem of generics and traits.

> I think that using a general Rust library would be fine since std essentially is just that and rbergen didn't see to have a problem with it when looking at my solution. Ultimately, I still respect your wish to not invite debate with the maintainers.

I think you're right about this, and Rayon is a pretty ubiquitous crate. It's probably OK.

> I think it is really unfortunate that those two forms of parallelism are treated the same. With fully independent parallel sieve solving, a near-linear speedup is to be expected as long as the cores don't exhaust some shared resource (which is unlikely with this type of workload, apart from boost clocks because of power).

I definitely agree with you here, and it would be better if they distinguished between the two different forms of parallelism. The fastest solution would probably be some hybrid of the two: a few threads working on a single sieve, within a larger set of parallel tasks running lots of sieves. 

> So in total, you seem to disagree with my proposal. As an alternative, would you agree to me partly reusing your code structure and also maybe make the BitVector variants generic to their inner type, so Rust can win with whatever type works best on Dave's machine?

I'd definitely be happy with you re-using some of the structures for your parallel implementations! It wouldn't be good using them for the single-threaded case though, as it duplicates what we have in this solution. 

For what it's worth, some time ago, I did have the original bit vector struct generic over the word type previously, but ultimately decided to remove it for the sake of simplicity. I found that u32 worked best, and just stuck with that. (A bit counterintuitive, as I'd fully expected u64 to be faster). Definitely give it a go on your parallel version though -- and let me know if you want me to pull code and run benchmarks.

**Comment by mike-barber** [comment]
> For what it's worth, some time ago, I did have the original bit vector struct generic over the word type previously, but ultimately decided to remove it for the sake of simplicity

I'm remembering this wrong. I didn't ever do generic bit vector storage :) I tested u8, u32 and u64. But never actually made it generic.

**Comment by Kulasko** [comment]
So to sum it up, I will try to aim for a generic approach similar to yours, while not using single threaded or fully parallel `base` algorithms. I think I will use `u8`, `u32` and `u64`. I haven't seen `u16` win in any of the other solutions, so I can save development and benchmark time here.

On that matter, I've seen a bit higher scores using nightly Rust. Nightly easily is stable enough for simple thing as this competition, but the standard Docker file doesn't feature it. There might be some merit of using nightly Rust through installing the toolchain during the Docker build stage, even if that results in a longer amount of time Docker needs to get ready.

**Comment by mike-barber** [comment]
Awesome, that will be great! And I'm happy to help out where I can. 

`nightly` is a good point -- I had never tested it. For `solution_1` it doesn't appear to make any difference on my machine (on stable 1.53 and 1.56.0-nightly). It's probably not something we need to worry about too much (for `solution_1` at least).

`cargo +nightly run --release 2> /dev/null`
```
mike-barber_byte-storage;18858;5.0001816750;1;algorithm=base,faithful=yes,bits=8
mike-barber_bit-storage;12151;5.0004401207;1;algorithm=base,faithful=yes,bits=1
mike-barber_bit-storage-rotate;13844;5.0002050400;1;algorithm=base,faithful=yes,bits=1
mike-barber_bit-storage-striped;18960;5.0003294945;1;algorithm=base,faithful=yes,bits=1
mike-barber_byte-storage;171469;5.0010285378;24;algorithm=base,faithful=yes,bits=8
mike-barber_bit-storage;135058;5.0011181831;24;algorithm=base,faithful=yes,bits=1
mike-barber_bit-storage-rotate;155044;5.0007095337;24;algorithm=base,faithful=yes,bits=1
mike-barber_bit-storage-striped;191162;5.0008625984;24;algorithm=base,faithful=yes,bits=1
```

`cargo +stable run --release 2> /dev/null`
```
mike-barber_byte-storage;18814;5.0002923012;1;algorithm=base,faithful=yes,bits=8
mike-barber_bit-storage;12123;5.0002746582;1;algorithm=base,faithful=yes,bits=1
mike-barber_bit-storage-rotate;14228;5.0003309250;1;algorithm=base,faithful=yes,bits=1
mike-barber_bit-storage-striped;19090;5.0001473427;1;algorithm=base,faithful=yes,bits=1
mike-barber_byte-storage;171406;5.0010924339;24;algorithm=base,faithful=yes,bits=8
mike-barber_bit-storage;135152;5.0008163452;24;algorithm=base,faithful=yes,bits=1
mike-barber_bit-storage-rotate;166363;5.0006771088;24;algorithm=base,faithful=yes,bits=1
mike-barber_bit-storage-striped;191364;5.0010232925;24;algorithm=base,faithful=yes,bits=1
```

**Comment by Kulasko** [comment]
Interesting. Maybe it did the loop unrolling you added manually now.

Anyway, since everything about this issue is clear on my front, I'm gonna close the Issue now.
